//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMCDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefinedDataArea
    {
        public string activeDirLogin { get; set; }
        public string areaId { get; set; }
        public string targetUrl { get; set; }
        public int recId { get; set; }
    }
}
